// Code generated by reactGen. DO NOT EDIT.

package book

import "myitcv.io/react"

func (q *QueryBooksDef) ShouldComponentUpdateIntf(nextProps, prevState, nextState interface{}) bool {
	res := false

	v := prevState.(QueryBooksState)
	res = !v.EqualsIntf(nextState) || res
	return res
}

// SetState is an auto-generated proxy proxy to update the state for the
// QueryBooks component.  SetState does not immediately mutate q.State()
// but creates a pending state transition.
func (q *QueryBooksDef) SetState(state QueryBooksState) {
	q.ComponentDef.SetState(state)
}

// State is an auto-generated proxy to return the current state in use for the
// render of the QueryBooks component
func (q *QueryBooksDef) State() QueryBooksState {
	return q.ComponentDef.State().(QueryBooksState)
}

// IsState is an auto-generated definition so that QueryBooksState implements
// the myitcv.io/react.State interface.
func (q QueryBooksState) IsState() {}

var _ react.State = QueryBooksState{}

// GetInitialStateIntf is an auto-generated proxy to GetInitialState
func (q *QueryBooksDef) GetInitialStateIntf() react.State {
	return q.GetInitialState()
}

func (q QueryBooksState) EqualsIntf(val interface{}) bool {
	return q == val.(QueryBooksState)
}
