// Code generated by reactGen. DO NOT EDIT.

package book

import "myitcv.io/react"

type MakeCollectionElem struct {
	react.Element
}

func buildMakeCollection(cd react.ComponentDef) react.Component {
	return MakeCollectionDef{ComponentDef: cd}
}

func buildMakeCollectionElem(props MakeCollectionProps, children ...react.Element) *MakeCollectionElem {
	return &MakeCollectionElem{
		Element: react.CreateElement(buildMakeCollection, props, children...),
	}
}

func (m MakeCollectionDef) RendersElement() react.Element {
	return m.Render()
}

// SetState is an auto-generated proxy proxy to update the state for the
// MakeCollection component.  SetState does not immediately mutate m.State()
// but creates a pending state transition.
func (m MakeCollectionDef) SetState(state MakeCollectionState) {
	m.ComponentDef.SetState(state)
}

// State is an auto-generated proxy to return the current state in use for the
// render of the MakeCollection component
func (m MakeCollectionDef) State() MakeCollectionState {
	return m.ComponentDef.State().(MakeCollectionState)
}

// IsState is an auto-generated definition so that MakeCollectionState implements
// the myitcv.io/react.State interface.
func (m MakeCollectionState) IsState() {}

var _ react.State = MakeCollectionState{}

// GetInitialStateIntf is an auto-generated proxy to GetInitialState
func (m MakeCollectionDef) GetInitialStateIntf() react.State {
	return MakeCollectionState{}
}

func (m MakeCollectionState) EqualsIntf(val react.State) bool {
	return m == val.(MakeCollectionState)
}

// IsProps is an auto-generated definition so that MakeCollectionProps implements
// the myitcv.io/react.Props interface.
func (m MakeCollectionProps) IsProps() {}

// Props is an auto-generated proxy to the current props of MakeCollection
func (m MakeCollectionDef) Props() MakeCollectionProps {
	uprops := m.ComponentDef.Props()
	return uprops.(MakeCollectionProps)
}

func (m MakeCollectionProps) EqualsIntf(val react.Props) bool {
	return m == val.(MakeCollectionProps)
}

var _ react.Props = MakeCollectionProps{}
