// Code generated by reactGen. DO NOT EDIT.

package book

import "myitcv.io/react"

type GetBookElem struct {
	react.Element
}

func buildGetBook(cd react.ComponentDef) react.Component {
	return GetBookDef{ComponentDef: cd}
}

func buildGetBookElem(props GetBookProps, children ...react.Element) *GetBookElem {
	return &GetBookElem{
		Element: react.CreateElement(buildGetBook, props, children...),
	}
}

func (g GetBookDef) RendersElement() react.Element {
	return g.Render()
}

// SetState is an auto-generated proxy proxy to update the state for the
// GetBook component.  SetState does not immediately mutate g.State()
// but creates a pending state transition.
func (g GetBookDef) SetState(state GetBookState) {
	g.ComponentDef.SetState(state)
}

// State is an auto-generated proxy to return the current state in use for the
// render of the GetBook component
func (g GetBookDef) State() GetBookState {
	return g.ComponentDef.State().(GetBookState)
}

// IsState is an auto-generated definition so that GetBookState implements
// the myitcv.io/react.State interface.
func (g GetBookState) IsState() {}

var _ react.State = GetBookState{}

// GetInitialStateIntf is an auto-generated proxy to GetInitialState
func (g GetBookDef) GetInitialStateIntf() react.State {
	return GetBookState{}
}

func (g GetBookState) EqualsIntf(val react.State) bool {
	return g == val.(GetBookState)
}

// IsProps is an auto-generated definition so that GetBookProps implements
// the myitcv.io/react.Props interface.
func (g GetBookProps) IsProps() {}

// Props is an auto-generated proxy to the current props of GetBook
func (g GetBookDef) Props() GetBookProps {
	uprops := g.ComponentDef.Props()
	return uprops.(GetBookProps)
}

func (g GetBookProps) EqualsIntf(val react.Props) bool {
	return g == val.(GetBookProps)
}

var _ react.Props = GetBookProps{}
